Change the output & Add logging & Signal handling
- Change per file system config
- Add signal handling and proper logging
- Add trap for handling the ERR and SIGINT

diff --git a/benchmark/common b/benchmark/common
--- a/benchmark/common
+++ b/benchmark/common
@@ -2,9 +2,54 @@
 [ -f config ]                 && . config
 [ -f `basename "$0"`.config ] && . `basename "$0"`.config
 
+. /etc/rc.d/init.d/functions
+
+cleanup ()
+{
+	rm -f $1
+}
+
 use()
 {
     echo ${benchmark_exclude} | grep -q -v -w `basename "$0"`
 }
 
-:
+run_benchmark()
+{
+	$@
+	ret=$?
+	echo
+	return ${ret}
+}
+
+error_occured()
+{
+    echo -e "BENCHMARK Error: $1\n" >> $logfile
+	cleanup $2
+}
+
+error_occured_workload()
+{
+    echo -e "BENCHMARK Error: $1\n" >> $logfile
+	kill -0 $3 && kill $3
+	cleanup $2
+}
+
+interrupt_exit()
+{
+	echo -e "BENCHMARK Interrupt: $1\n" >> $logfile
+	cleanup $2
+	exit 1
+}
+
+interrupt_exit_workload()
+{
+	echo -e "BENCHMARK Interrupt: $1\n" >> $logfile
+	kill -0 $3 && kill $3
+	cleanup $2
+	exit 1
+}
+
+
+
+
diff --git a/benchmark/macro-fio-grep b/benchmark/macro-fio-grep
--- a/benchmark/macro-fio-grep
+++ b/benchmark/macro-fio-grep
@@ -1,12 +1,17 @@
-#! /bin/bash -e
+#! /bin/bash 
 
 cd `dirname "$0"`
 . common
 
 fio_run()
 {
+	echo -e "Starting `basename "$0"`..."
 	export mount_dir RW
-	fio --output-format=json --output=${result} `basename "$0"`.job 
+    trap 'error_occured "${result}" "${result}"' ERR 
+    trap 'interrupt_exit "${result}" "${result}"' SIGINT
+	#fio --output-format=json --output=${result} `basename "$0"`.job && (echo; success) || (echo; failure)
+	benchmark_command="fio --output-format=json --output=${result} `basename "$0"`.job"
+	action "" run_benchmark ${benchmark_command}
 }
 
 case "$1" in
diff --git a/iosched/common b/iosched/common
--- a/iosched/common
+++ b/iosched/common
@@ -2,9 +2,20 @@
 [ -f config ]                 && . config
 [ -f `basename "$0"`.config ] && . `basename "$0"`.config
 
+. /etc/rc.d/init.d/functions
+
 use()
 {
     echo ${iosched_exclude} | grep -q -v -w `basename "$0"`
 }
 
-:
+error_exit()
+{
+    echo -e "IOSCHEDULER Error: $1\n" >> $logfile
+    exit 1
+}
+
+change_ioscheduler()
+{
+	echo "$1" > "$2"
+}
